[Synthèse] Tests/synthese routes
PnX-SI/GeoNature pull request #1605
Opened 2022-01-13 20:24 UTC by mvergez

Ajout de tests des routes de la Synthèse
Corrections sur les tests déjà définis

2022-01-13 23:42 UTC, bouttier requested changes

2022-01-13 23:42 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +    # synthese_query_class.filter_query_all_filters(info_role)
^

2022-01-13 23:42 UTC, bouttier commented on backend/geonature/tests/test_synthese.py
> +HIGH_ID = 12000
Exemple tiré de test_gn_commons :
unexisting_id = db.session.query(func.max(TPlaces.id_place)).scalar() + 1

2022-01-17 07:58 UTC, mvergez commented on backend/geonature/core/gn_synthese/routes.py
> +    # synthese_query_class.filter_query_all_filters(info_role)
C'est corrigé ! Merci !

2022-01-17 08:00 UTC, mvergez commented on backend/geonature/tests/test_synthese.py
> +HIGH_ID = 12000
Merci pour l'astuce ! 
Corrigé avec une fixture : 
```python
@pytest.fixture()
def unexisted_id():
    return db.session.query(func.max(TDatasets.id_dataset)).scalar() + 1
```
Utilisé aussi dans les test_metadata : à voir si on le mets dans `fixtures.py`

2022-01-17 15:30 UTC, merged