Docker
PnX-SI/GeoNature pull request #1655
Opened 2022-01-26 11:59 UTC by antoinececchimnhn

2022-01-26 13:11 UTC, bouttier commented on docker/backend/.env.sample
> +install_module_occhab=false
≠ INSTALL_OCCHAB ?

2022-01-26 13:11 UTC, bouttier commented on .env.local
> +nomenclature_release=1.3.8
pourquoi faut-il les spécifier là ?

2022-01-26 13:11 UTC, bouttier commented on entrypoint.sh
> +echo "URL_APPLICATION = 'http://${HOST_FRONT}'" >> config/geonature_config.toml
il faudrait que l’on puisse dire qu’on utilise de l’https

2022-01-26 15:35 UTC, antoinececchimnhn commented on docker/backend/Dockerfile
> +FROM python:3.7-buster
Oui ça doit pas poser de pbs

2022-01-26 15:36 UTC, antoinececchimnhn commented on apt-packages.txt
> +postgresql-11-postgis-2.5
Ouep, on peut regarder pour faire ça

2022-01-26 15:37 UTC, antoinececchimnhn commented on .env.local
> +nomenclature_release=1.3.8
C'est probablement du legacy du settings.ini

2022-01-26 15:38 UTC, antoinececchimnhn commented on entrypoint.sh
> +echo "URL_APPLICATION = 'http://${HOST_FRONT}'" >> config/geonature_config.toml
Il me semble que traefik peut automatique rediriger vers l'https mais à creuser, sinon on mettra ça dans les variables d'env sans soucis

2022-01-26 15:39 UTC, antoinececchimnhn commented on entrypointfront.sh
> +cp src/custom/components/introduction/introduction.component.html.sample src/custom/components/introduction/introduction.component.html
Oui ça doit être faisable. A voir si on ne lancerait pas tout simplement le 04_install_frontend d'ailleurs

2022-01-26 16:07 UTC, jpm-cbna reviewed
Pour les fichiers .env, je me demandai s'il n'y aurait pas un moyen de simplifier le nombre de ligne en réutilisant les fichiers de config classique de GN.
Le fait de les répéter ici dans les fichiers ".env"  ajoute un nouveau lieu où il faut faire des modifications si on renomme une variable...

2022-01-26 16:07 UTC, jpm-cbna commented on docker/Readme.md
> +### GeoNature sur un environnement local (Développement)
Y a t il une raison technique au fait d'avoir séparé le front et le back dans 2 fichiers docker-compose distinct ?

Il n'était pas envisageable de les rassembler dans un seule fichier sous forme [de services dépendants](https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on) ?

2022-01-26 16:07 UTC, jpm-cbna commented on docker-compose.local.yml
> +  adminer:
Pourquoi mettre le service "adminer" ici, il ne devrait pas plutôt être avec la base de données ?

2022-01-26 16:45 UTC, bouttier commented on entrypointfront.sh
> +cp src/custom/components/introduction/introduction.component.html.sample src/custom/components/introduction/introduction.component.html
S’il faut simplifier le ``04_install_frontend.sh`` pour que ça soit possible, profitons-en :-)

2022-01-27 07:42 UTC, antoinececchimnhn commented on docker/frontend/docker-compose.yml
> +version: '3.2'
Oui tout à fait

2022-01-27 07:43 UTC, antoinececchimnhn commented on docker/Readme.md
> +### GeoNature sur un environnement local (Développement)
La raison principale est juste que ça permet d'avoir des traces distinctes pour les logs consoles

2022-01-27 07:44 UTC, antoinececchimnhn commented on docker-compose.local.yml
> +  adminer:
C'est vrai, je le décalle sur le service bdd

2022-01-27 15:42 UTC, antoinececchimnhn commented on apt-packages.txt
> +postgresql-11-postgis-2.5
Pour tous les modules dont les migrations se font via Alembiec je pense qu'il n'y e a pas besoin

2022-01-27 15:44 UTC, antoinececchimnhn commented on docker/backend/.env.sample
> +install_module_occhab=false
Heu non =

2022-01-28 14:43 UTC, antoinececchimnhn commented on entrypoint.sh
> +#! /bin/sh
Il est effectivement possible qu'on puisse encore déplacer des installations sur le Dockerfile, en l'état toutes les lib apt et pip sont installées dans le docker file, côté npm ça pourrait peut être intéressante. 

Toutefois l'entrypoint doit quand même faire un certain nombre de choses qui nécessitent un accès à la base (installation de modules, migrations ect...)

2022-01-28 14:45 UTC, antoinececchimnhn commented on docker/Readme.md
> +Les installations de docker engine et docker compose se font en suivant le guide officiel:
Je l'ai laissé notamment pour les utilisateurs mac et windows. J'ai déjà eu des problèmes avec des installations "trop rapides" de docker donc je préfère prévenir :stuck_out_tongue_closed_eyes:

2022-02-07 07:41 UTC, mvergez requested changes
Salut !
J'ai fait quelques remarques notamment sur le nombre de layers créées dans tes dockerfile. Il faudrait les réduire pour réduire le temps de build et surtout la taille de l'image à la fin. A voir aussi si un multistage build ne pourrait pas être utilisé pour réduire encore plus la taille, mais ça me semble difficile ici...
Questionnement sur le build du frontend à mettre dans le dockerfile du frontend

2022-02-07 07:41 UTC, mvergez commented on docker/Readme.md
> +### GeoNature sur un environnement local (Développement)
Je suis d'accord avec @jpm-cbna. Si je ne dis pas de bêtises, docker-compose te crée des conteneurs séparés (2 services différents) donc tu peux avoir les logs pour un service seulement avec `docker-compose logs <mon_service>`. C'est ces logs là dont tu parles @antoinececchimnhn ?

2022-02-07 07:41 UTC, mvergez commented on docker/backend/Dockerfile
> +RUN export LANG=fr_FR.UTF-8
Arriverais-tu à fusionner ces commandes RUN ? Cela permettrait de créer moins de layers donc de générer plus rapidement l'image et de diminuer sa taille finale https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#minimize-the-number-of-layers

2022-02-07 07:41 UTC, mvergez commented on docker/backend/Dockerfile
> +COPY apt-packages.txt /GeoNature
COPY va créer une nouvelle layer, peut-être est-ce plus intéressant de mettre directement les packages apt dans le apt-get install ci-dessous pour minimiser le nombre de layers

2022-02-07 07:41 UTC, mvergez commented on docker/backend/Dockerfile
> +COPY ./install/install_all/install_all.sh /GeoNature
Le dossier ./install/install_all n'est pas déjà copié par la commande `COPY . /GeoNature/` ?

2022-02-07 07:41 UTC, mvergez commented on docker/backend/Dockerfile
> +RUN pip3 install -e /GeoNature/contrib/gn_module_occhab
Possibilité je pense de fusionner en un seul RUN

2022-02-07 07:41 UTC, mvergez commented on docker/backend/Dockerfile
> +RUN mkdir /GeoNature/frontend
Ces `mkdir` sont-ils vraiment nécessaires ? Le `COPY` ci-dessous ne va-t-il pas les créer automatiquement ?

2022-02-07 07:41 UTC, mvergez commented on docker/frontend/Dockerfile
> +EXPOSE 80
Pourquoi ne pas mettre le build du frontend ici ? Exemple pris de citizen : 
```dockerfile
# STAGE INSTALL NODE_MODULES
FROM node:14 as builder

COPY ./package.json ./package-lock.json /

RUN npm install

# STAGE RUNTIME
FROM builder as runtime

WORKDIR /app

COPY --from=builder /node_modules ./node_modules
COPY . .

RUN npm run build:i18n-ssr
```

Dans citizen, le frontend n'est pas compilé en html js mais servi directement par node (SSR) mais ici on pourrait rajouter un stage en plus du style : 
```dockerfile
FROM nginx:1.16.1
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Ajouter le COPY --from=runtime du html et du js ici
```
Il doit sûrement y avoir des limitations dues à la structure de GeoNature que je dois oublier qui empêcheraient de faire tout ça non ? 
Qu'en penses-tu ?

2022-02-07 07:41 UTC, mvergez commented on docker/frontend/DockerfileLocal
> +RUN apt-get install -y python3
Possibilité de merger ces RUN

2022-02-07 07:41 UTC, mvergez commented on docker/frontend/DockerfileLocal
> +RUN mkdir /root/.cache
Toutes ces lignes du RUN chown au RUN mkdir sont réellement nécessaires ? Je ne comprends pas pourquoi il faudrait créer un utilisateur node ici...

2022-02-07 07:41 UTC, mvergez commented on entrypointfront.sh
> +cp src/custom/components/introduction/introduction.component.html.sample src/custom/components/introduction/introduction.component.html
A mettre du coup dans le build de `frontend/Dockerfile` ?

2022-02-07 08:47 UTC, antoinececchimnhn commented on docker/frontend/Dockerfile
> +EXPOSE 80
C'est ce que je voulais faire initialement, Malheureusement pour l'heure c'est rendu compliqué par la création de fichier de conf du front "côté backend". C'est pour ça que le build du front n'est pas fait dans un dockerfile, ce qui nous permettrait effectivement de déployer des images ne contenant que des fichiers statics comme tu le proposes ici

2022-02-07 08:48 UTC, antoinececchimnhn commented on docker/frontend/DockerfileLocal
> +RUN mkdir /root/.cache
Simplement pour éviter de rester root, je voulais me pencher sur le sujet pour l'ensemble des Dockerfile

2022-02-07 08:49 UTC, antoinececchimnhn commented on docker/frontend/Dockerfile
> +EXPOSE 80
De même du coup pour l'instant les custom files pourront difficilement être déplacés

2022-02-07 10:54 UTC, mvergez commented on docker/frontend/Dockerfile
> +EXPOSE 80
Oui ça rend effectivement la chose beaucoup plus complexe... Je vais réfléchir à une solution, car ça permettrait de commencer la séparation entre backend/frontend/bdd etc...

2022-02-07 10:55 UTC, mvergez commented on docker/frontend/DockerfileLocal
> +RUN mkdir /root/.cache
Tu veux éviter d'être root pour les problèmes de droits sur les volumes ?

2022-02-07 11:43 UTC, antoinececchimnhn commented on docker/frontend/Dockerfile
> +EXPOSE 80
Tout à fait et ça permettrait à terme de réduire (très) fortement les downtime pendant les mises à jour de GeoNature. Il n'y en aurait éventuellement que le temps que les migrations se fassent

2022-02-07 11:44 UTC, antoinececchimnhn commented on docker/frontend/DockerfileLocal
> +RUN mkdir /root/.cache
Non plus parce que côté MNHN on a pour consigne de dropper les droits roots dès que possible sur nos images

2022-02-07 11:44 UTC, antoinececchimnhn commented on docker/backend/Dockerfile
> +RUN mkdir /GeoNature/frontend
Hmmm bonne question, à tester

2022-02-07 14:40 UTC, mvergez commented on docker/frontend/DockerfileLocal
> +RUN mkdir /root/.cache
Tu as plus d'info sur cette consigne ? Cela aurait uniquement un impact sur les volumes montés ou si les conteneurs sont lancés en mode priviledge non ?

2022-02-07 14:41 UTC, mvergez commented on docker/frontend/Dockerfile
> +EXPOSE 80
Complétement d'accord

2025-04-11 14:01 UTC, closed without merging