#1688 - Modification sur mode dev et ajout de compléments
PnX-SI/GeoNature pull request #1697
Opened 2022-02-10 17:29 UTC by Gaetanbrl

Link to 1688 issue

2022-02-16 17:44 UTC, bouttier commented on docs/development.rst
> +Remplacez dans ce fichier la valeur de ``ID_APPLICATION_GEONATURE`` pour mettre la valeur récupérée plus haut.
Inutile, l’`ID_APP` est auto-détecté.

2022-02-16 17:49 UTC, bouttier commented on docs/development.rst
> +API en développement
Cete section me semble faire redite avec la section existante « Développement Backend ». Plutôt mettre un lien vers la section existante ?

2022-02-16 17:49 UTC, bouttier commented on docs/development.rst
> +  cd backend
Inutile de se rendre dans le dossier `backend` pour lancer `dev_back`.

2022-02-16 18:10 UTC, Gaetanbrl commented on docs/development.rst
> +  npm run start
Les deux commandes peuvent en effet figurée dans la doc.

J'utilise pm2 pour lancer le service (npm) au démarrage de ma VM et je trouve toutefois assez perturbant d'exécuter du front npm ou node avec une stack python si elle ne fait que exécuter la même commande.

Quels sont les avantages de la commande `geonature` dans ce contexte ? Est-ce préférable ou juste une alternative ?

2022-02-16 18:17 UTC, bouttier commented on docs/development.rst
> +  npm run start
C’est totalement équivalent.
Les avantages que je vois à `dev_front` sont :
- homogénéité avec `dev_back`
- peut être lancé depuis n’importe quel dossier
- si les paramètres de npm évolue, on pourra le faire dans la commande GeoNature

Je pense qu’il est préférable que la doc soit au plus simple, donc `dev_front`, mais ne te prive pas de lancer `npm` toi même !

2022-02-17 09:43 UTC, Gaetanbrl commented
@bouttier modifications appliquées. Merci pour la revue.

2022-02-17 09:49 UTC, camillemonchicourt commented
Merci, ça a été l'occasion d'une bonne mise à jour.

2022-02-17 09:51 UTC, bouttier requested changes
Merci pour la contrib, dernière petite remarque.

2022-02-17 09:51 UTC, bouttier commented on docs/development.rst
> +Récupération de l'ID de l'application GeoNature
Du coup cette section devient inutile.

2022-02-17 13:58 UTC, Gaetanbrl commented
> Merci pour la contrib, dernière petite remarque.

C'est modifié. merci !

2022-02-17 14:33 UTC, merged