Discussion validateur et ou synthese
PnX-SI/GeoNature pull request #1774
Opened 2022-03-14 16:45 UTC by Gaetanbrl

_Ref. issue #1737_ 

> Cette contribution a été réalisée selon les besoins de [picardie-nature](http://www.picardie-nature.org/) et en accord avec les principes de la communauté GeoNature

Cette PR permet d'ajouter un onglet "Discussion" dans le module VALIDATION et / ou SYNTHESE selon les détails fourni dans l'issue 1737.

Les éléments suivants on été modifié ou rajoutés : 

* Nouvelle table `t_reports` qui sera utilisée par d'autres features à venir (e.g signalement) avec[ le fichier Alembic associé](https://github.com/picardie-nature/GeoNature/blob/feature-1731-dev/backend/geonature/migrations/versions/5094d05780ac_add_table_gn_synthese_t_reports.py)
* Ajout de [nouvelles routes](https://github.com/picardie-nature/GeoNature/blob/feature-1731-dev/backend/geonature/core/gn_synthese/routes.py#L940) pour le CRUD d'un élément de la table `t_report` (nommé `report`)
* Ajout de deux paramètres optionnels : 

https://github.com/picardie-nature/GeoNature/blob/fd35700a8bf52d63dc60ee2477ef92f716307246/backend/geonature/utils/config_schema.py#L288-L290

**Je pense qu'un squash est à prévoir pour le merge.**

**Les tests backend sont en option et viendront potentiellement compléter cette PR (non confirmé et en accord avec les échanges passés avec la communauté GeoNature).**

2022-03-16 17:55 UTC, camillemonchicourt commented on backend/geonature/core/gn_synthese/routes.py
> +def create_discussion():
Report ou discussion ? A mettre en cohérence je pense.
Idem un peu partout dans ce commit, et même dans les noms de paramètre.
Je comprends pas bien qu'on parle parfois de discussion et parfois de report ?

2022-03-16 17:56 UTC, camillemonchicourt commented
La référence au ticket ne semble pas la bonne et plutôt être : https://github.com/PnX-SI/GeoNature/issues/1731.

Les tests ne sont pas passés sur la partie Alembic si je comprends bien.

2022-03-16 18:04 UTC, bouttier commented on backend/geonature/migrations/versions/5094d05780ac_add_table_gn_synthese_t_reports.py
> +down_revision = '1dbc45309d6e'
La nouvelle head de la branche ``geonature`` est ``ca052245c6ec``.

2022-03-17 08:30 UTC, Gaetanbrl commented on backend/geonature/migrations/versions/5094d05780ac_add_table_gn_synthese_t_reports.py
> +        id_module integer NOT NULL,
En effet, c'était utile jusqu'au dernières évolution demandées S-1 (certains commentaires à afficher selon SYNTHESE  ou VALIDATION).

2022-03-17 08:32 UTC, Gaetanbrl commented on backend/geonature/migrations/versions/5094d05780ac_add_table_gn_synthese_t_reports.py
> +        content_owner json NOT NULL,
Le champ id_role permettra de réaliser un filtre sur l'id_role via un paramètre URL directement (obligatoire pour l'évolution signalement à venir).
Les autres informations content_owner permettent d'avoir les infos directement sans appels serveur (évite des appels inutiles) pour afficher les infos du user en en-têtes de commentaire.

2022-03-17 08:39 UTC, Gaetanbrl commented on backend/geonature/migrations/versions/5094d05780ac_add_table_gn_synthese_t_reports.py
> +        content_report json NOT NULL,
> date ou creation_date

"date" est un nom de champ souvent réservé (c'est aussi un format).

> On a plutôt l'habitude de stocker les champs de texte en format text et pas json.

Cela permet d'avoir plus de souplesse pour ajouter par exemple une info dans du contenu qui serait lié à un usage spécifique sans avoir à rajouter des champs (pour éviter une table usine à gaz). J'ajoute par exemple dans ce JSON un attribut "deleted" pour savoir si le champ a été supprimé (c.f les dernières demande d'évolutions pour ne pas le supprimer et voir qu'il a été supprimé à la place).
Le type JSON est une pratique très utile !

> une  clé étrangère vers un bibliothèque des types de reports existants

On y a pensé, mais on s'est dit que ce serait rajouter encore un élément complexe...


> Donc plutôt le nommer content ou report

Je peux renommer.

2022-03-17 08:40 UTC, Gaetanbrl commented on backend/geonature/core/gn_synthese/routes.py
> +def create_discussion():
> Je comprends pas bien qu'on parle parfois de discussion et parfois de report

Des modifications ont été faite en cours en lien avec l'issue sur les signalements, ce sont des oublis.

2022-03-17 08:42 UTC, Gaetanbrl commented on backend/geonature/migrations/versions/5094d05780ac_add_table_gn_synthese_t_reports.py
> +down_revision = '1dbc45309d6e'
Oui j'ai regénéré le fichier hier. Pas toujours évident de rester à jour entre tous les travaux en cours / tests à refaire ;)

2022-03-17 08:55 UTC, Gaetanbrl commented
> La référence au ticket ne semble pas la bonne et plutôt être : #1731.
> 
> Les tests ne sont pas passés sur la partie Alembic si je comprends bien.

Non la branche alembic a évoluée depuis la création de ce fichier...

2022-03-17 09:06 UTC, Gaetanbrl commented on backend/geonature/migrations/versions/5094d05780ac_add_table_gn_synthese_t_reports.py
> +        content_report json NOT NULL,
> une clé étrangère vers un bibliothèque des types de reports existants

Je vais créer une table pour lister les type ce sera plus simple à comprendre et pour mieux gérer les différents types qui vont arriver ;)

2022-03-17 09:13 UTC, camillemonchicourt commented on backend/geonature/migrations/versions/5094d05780ac_add_table_gn_synthese_t_reports.py
> +        id_module integer NOT NULL,
OK donc à supprimer désormais je dirai.

2022-03-17 09:16 UTC, camillemonchicourt commented on backend/geonature/migrations/versions/5094d05780ac_add_table_gn_synthese_t_reports.py
> +        content_owner json NOT NULL,
On ne duplique pas les infos en json dans la BDD de GeoNature, on garde bien le fonctionnement des relations SQL pour ne pas dupliquer des infos, devoir les mettre à jour si le nom de l'utilisateur change, etc...
Donc pour garder une BDD "propre" et relationnelle, il faudrait supprimer ce champs ``content_owner`` et bien faire une jointure dans les requêtes pour récupérer les infos sur l'auteur.

2022-03-17 09:24 UTC, Gaetanbrl commented on backend/geonature/migrations/versions/5094d05780ac_add_table_gn_synthese_t_reports.py
> +        id_module integer NOT NULL,
En cours ;)

2022-03-17 09:25 UTC, camillemonchicourt commented on backend/geonature/migrations/versions/5094d05780ac_add_table_gn_synthese_t_reports.py
> +        content_report json NOT NULL,
OK donc pour éviter un champs ``date``, je suggère de le renommer ``creation_date`` ou ``date_creation``. C'est la date de création du report dans sa totalité, pas du contenu.

Pour le champs contenant le contenu du commentaire en json, c'est vraiment pas l'approche que l'on a dans GeoNature.
On a une approche DB-first où l'on essaie de structurer et typer au mieux les champs et les relations.
On préfère clairement un champs ``content`` en format text et un booléen ``deleted`` si besoin.

Idem pour la table des types, on fonctionne comme ça partout dans GeoNature, en privilégiant avant tout, la structure de la BDD comme référence.
Cette table des types serait ``bib_report_types`` avec un champs ``id_type`` (integer Serial) et un champs ``type`` (varchar).

2022-03-17 09:26 UTC, camillemonchicourt commented on backend/geonature/migrations/versions/5094d05780ac_add_table_gn_synthese_t_reports.py
> +down_revision = '1dbc45309d6e'
Oui exact, les révisions Alembic ont bougé depuis, bien vu.

2022-03-17 09:35 UTC, Gaetanbrl commented on backend/geonature/migrations/versions/5094d05780ac_add_table_gn_synthese_t_reports.py
> +down_revision = '1dbc45309d6e'
On réalise des déploiement sur une PF de test, ca permet de voir si tout fonctionne de temps en temps (bon parfois les tests sont fait avant que GeoNature ne re bouge mais c'est la vie du projet ;) )

2022-03-17 09:38 UTC, Gaetanbrl commented on backend/geonature/migrations/versions/5094d05780ac_add_table_gn_synthese_t_reports.py
> +        content_report json NOT NULL,
C'est noté, je fais les modifications en ce sens.
Par contre, quelle est la signification de bib ?

2022-03-17 09:42 UTC, Gaetanbrl commented on backend/geonature/migrations/versions/5094d05780ac_add_table_gn_synthese_t_reports.py
> +        content_owner json NOT NULL,
Donc je vais adapter le code et faire la jointure après récupération des reports :
1. Appel (GET)
2. Récupération des reports en base
3. Joindre les infos sur l'id_role ==> in progress
4. Retourner au front les reports (JSON)

2022-03-17 10:28 UTC, Gaetanbrl commented on backend/geonature/migrations/versions/5094d05780ac_add_table_gn_synthese_t_reports.py
> +        content_report json NOT NULL,
En l'état je vais rester cohérent avec l'existant et garder `bib_`. Si `dict_` est amené a être utilisé, ce sera une modification mineure.

2022-03-17 14:21 UTC, TheoLechemia commented
J'ai des erreurs 500 lorsque j'essaye de faire une review, donc je les met là : 

Pour moi le modèle devrait s’appeller `TReport` comme le nom de la table en BDD. Le cor laisse pensé qu'il s'agit d'une table "n-n". 
Pour la jointure, il faut privilégier l'utilisation des relationships dans les modèles. Et pour la serialisation, voir la doc ici : https://docs.geonature.fr/development.html#avec-marshmallow

@bouttier rajoute : 
En effet, la requête correcte se résume à `TReport.query.filter_by(id_synthese=synthese).options(joinedload('user')).all()`

@Gaetanbrl on t'a mis plus de détail sur matrix

2022-03-17 15:36 UTC, Gaetanbrl commented
@TheoLechemia github est down depuis une heure
https://www.githubstatus.com/

2022-03-17 18:40 UTC, Gaetanbrl commented
La PR en l'état fonctionne et correspond aux besoins.

Cependant, suite à discussions avec @TheoLechemia et @bouttier il est demandé d'utiliser `sqlalchemy.orm` et de ne pas faire de jointure directement avec `sqlalchemy` sans l'ORM (méthode actuellement utilisée dans cette PR car constatée dans le code GeoNature).

Ce point étant clairement "préférable" pour les nouveaux développement, les travaux sont en cours sur cette PR pour aller dans ce sens.

2022-03-18 10:54 UTC, Gaetanbrl commented
problème sur le head / alembic à corriger... encore.

2022-03-21 08:53 UTC, Gaetanbrl commented
@TheoLechemia @bouttier @camillemonchicourt la PR me semble prête suite à vous revues :

- [ ] Utilisation SQLAlchemy ORL (relation entre table User et TReport)
- [ ] Ajout de tests backend (optionnel)
- [ ] Fix & Update des révisions alembic table `t_report` et `bib_reports_types`

2022-03-21 17:30 UTC, bouttier requested changes
J’ai fais pas mal de petites remarques sur l’API, notamment lié aux permissions.
Les précédents retours avaient bien été pris en compte, ok pour moi, merci !

2022-03-21 17:30 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +        row.deleted = data["deleted"]
Pour simplifier et clarifier le fonctionnement, je préférerai que la route delete s’occupe de marquer les commentaires à supprimé, et que la route d’update se limite à la modification du commentaire.

2022-03-21 17:30 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +    id_report = request.args.get("idReport")
Pour la suppression du filtre par ``id_report``. En fait cette route est plutôt une ``list_reports`` qu’un ``get_report``. Si on veut un report par id, on implémentera une autre route (car différent type de retour, liste vs report unique).

2022-03-21 17:30 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +    req = TReport.query.filter(TReport.id_synthese==id_synthese)
À rajouter avant :
```
synthese = Synthese.query.get_or_404(id_synthese)
if not synthese.has_instance_permission(scope):
    raise Forbidden
```

2022-03-21 17:30 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +@routes.route('/reports', methods=["GET"])
```
@permissions.check_cruved_scope("R", get_scope=True, module_code="SYNTHESE")
def list_reports(scope):
```

2022-03-21 17:30 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +        req = req.filter(TReport.id_role==id_role)
Filtre à priori peu pertinent et curieux, je suis pour sa suppression.

2022-03-21 17:30 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +        req = req.filter(TReport.id_report==id_report)
Filtre à supprimer (préférer une route ``get_report(id_report)`` si nécessaire).

2022-03-21 17:30 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +    return jsonify({"results": result})
```return jsonify(result)```

2022-03-21 17:30 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +@json_resp
``@login_required``

2022-03-21 17:30 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +    DB.session.delete(reportItem)
du coup à priori ``reportItem.deleted = True``

2022-03-21 17:30 UTC, bouttier commented on contrib/gn_module_validation/frontend/app/services/data.service.ts
> +    return this._http.delete(`${AppConfig.API_ENDPOINT}/synthese/reports${id}`)
``reports/${id}`` non ?

2022-03-22 08:42 UTC, pierrejego commented on backend/geonature/core/gn_synthese/routes.py
> +        req = req.filter(TReport.id_role==id_role)
Ce filtre est nécessaire dans le cas de l'épinglage. Uniquement le user qui a épinglé la synthèse doit le voir

2022-03-22 08:47 UTC, pierrejego commented on contrib/gn_module_validation/frontend/app/services/data.service.ts
> +    return this._http.delete(`${AppConfig.API_ENDPOINT}/synthese/reports${id}`)
bien vu correction faite [36374f1](https://github.com/PnX-SI/GeoNature/pull/1774/commits/36374f13e2a10ddcd72e6d000b9e9899c189d4c3)

2022-03-22 08:47 UTC, pierrejego commented on config/default_config.toml.example
> +    DICUSSION_LENTH = 1500
Modification faite [43ad456](https://github.com/PnX-SI/GeoNature/pull/1774/commits/43ad456a7621ece716c8a89f86c4a409027fbda8)

2022-03-22 08:49 UTC, pierrejego commented on backend/geonature/core/gn_synthese/models.py
> +
modification faite

2022-03-22 08:49 UTC, pierrejego commented on backend/geonature/core/gn_synthese/routes.py
> +    new_entry = TReport(
modification faite

2022-03-22 08:49 UTC, pierrejego commented on backend/geonature/core/gn_synthese/routes.py
> +@json_resp
ajouté

2022-03-22 08:50 UTC, pierrejego commented on backend/geonature/core/gn_synthese/routes.py
> +@routes.route('/reports', methods=["GET"])
ajouté

2022-03-22 08:50 UTC, pierrejego commented on backend/geonature/core/gn_synthese/routes.py
> +    id_report = request.args.get("idReport")
modification faite

2022-03-22 08:51 UTC, pierrejego commented on backend/geonature/core/gn_synthese/routes.py
> +    req = TReport.query.filter(TReport.id_synthese==id_synthese)
ok

2022-03-22 08:54 UTC, pierrejego commented on backend/geonature/core/gn_synthese/routes.py
> -@permissions.check_cruved_scope("E", True, module_code="SYNTHESE")
une erreur oui

2022-03-22 09:00 UTC, Gaetanbrl commented on backend/geonature/core/gn_synthese/routes.py
> +        row.deleted = data["deleted"]
Donc DELETE va modifier un champ et UPDATE modifier le contenu ?
Il faut garder en tête que la route DELETE permettra surtout de supprimer des épingles ou signalements (autres évolutions à venir) vu qu'on a utilisé une table pour les trois à votre demande. Cette route DELETE n'est pas utilisée pour un commentaire car la fonctionnalité de suppression a été enlevée suite à vos retours.

Donc je reste un peu confus sur ce point.

2022-03-22 09:07 UTC, Gaetanbrl commented on backend/geonature/core/gn_synthese/models.py
> +    id_synthese = DB.Column(DB.Integer())
Modifié

2022-03-22 09:08 UTC, Gaetanbrl commented on backend/geonature/core/gn_synthese/routes.py
> +def create_report():
C'était une question qu'on avait déjà posé en effet. Merci pour le partage du code.
==> Modifié.

2022-03-22 09:11 UTC, Gaetanbrl commented on backend/geonature/core/gn_synthese/routes.py
> +def create_report():
> module_code="SYNTHESE"
@bouttier est-ce que la précision du code module va faire que dans le module VALIDATION, la lecture des commentaires sera bloquées ?

2022-03-22 09:13 UTC, Gaetanbrl commented on backend/geonature/core/gn_synthese/routes.py
> +            raise Forbidden()
Fait.

2022-03-22 09:15 UTC, Gaetanbrl commented on backend/geonature/core/gn_synthese/routes.py
> +            raise Forbidden()
fait.

2022-03-22 09:17 UTC, Gaetanbrl commented on backend/geonature/core/gn_synthese/routes.py
> +    g.current_user = user_from_token(request.cookies['token']).role
Fait.

2022-03-22 09:22 UTC, Gaetanbrl commented on backend/geonature/core/gn_synthese/routes.py
> +        raise NotFound(f"This report can't be update by {g.current_user}")
`raise Forbidden` est inutile avec get_or_404 c'est cela ?

2022-03-22 09:24 UTC, Gaetanbrl commented on backend/geonature/core/gn_synthese/routes.py
> +    DB.session.delete(reportItem)
non, on veut pouvoir supprimer un éléments (voir commentaire précédent). Le delete n'est pas utilisé pour les commentaires.

2022-03-22 09:43 UTC, Gaetanbrl commented on backend/geonature/core/gn_synthese/routes.py
> +    return jsonify({"results": result})
Fait.

2022-03-22 09:45 UTC, Gaetanbrl commented on backend/geonature/core/gn_synthese/routes.py
> +        req = req.filter(TReport.id_report==id_report)
En prévision ==> inutile dans cette PR.
Filtre supprimé.

2022-03-22 09:51 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +        raise NotFound(f"This report can't be update by {g.current_user}")
Si si il est utile ! Ma remarque c’est que dans ton code, si l’utilisateur n’est pas le bon, alors on ``raise NotFound``. Mais je préfère que si l’utilisateur n’est pas le bon, bien que l’``idReport`` existe, on ``raise Forbidden``, et qu’on lève une 404 uniquement pour le cas où l’``idReport`` n’existe pas.

2022-03-22 09:51 UTC, Gaetanbrl commented on backend/geonature/core/gn_synthese/routes.py
> +        raise NotFound(f"This report can't be update by {g.current_user}")
Fait.

2022-03-22 09:56 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +        row.deleted = data["deleted"]
Donc si je résume le comportement souhaité, lorsque l’on supprime un « report », si c’est un commentaire on le marque supprimé, mais si c’est une épingle ou signalement, on le supprime de la base.

Bien que la suppression d’un commentaire n’entraîne pas sa suppression de la base, je reste pour avoir une API simple, avec la route d’UPDATE qui met à jour le champs ``content`` uniquement, et la route DELETE qui implémente la logique suppression ou marquage comme supprimé suivant le type de « report ».

2022-03-22 09:57 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +def create_report():
Bien vu ! Effectivement après vérification, le module VALIDATION utilise son propre module_code y compris pour l’accès aux observations, donc ça va poser problème. On en discute en interne et je reviens.

2022-03-22 10:02 UTC, Gaetanbrl commented on backend/geonature/core/gn_synthese/routes.py
> +            raise Forbidden()
code ajouté `@permissions.check_cruved_scope("R", get_scope=True, module_code="SYNTHESE")`

2022-03-22 10:26 UTC, Gaetanbrl commented on backend/geonature/migrations/versions/829a376daa52_add_table_gn_synthese_t_reports.py
> +            ON UPDATE CASCADE ON DELETE CASCADE
Fait.

2022-03-22 10:35 UTC, Gaetanbrl commented on backend/geonature/core/gn_synthese/routes.py
> +        row.deleted = data["deleted"]
> je résume le comportement souhaité[...]

Oui c'est tout à fait ça, c'est du moins ce qui avait été convenu avec @jbdesbas et @camillemonchicourt 

> et la route DELETE qui implémente la logique suppression ou marquage comme supprimé suivant le type de « report »

Cet approche peut convenir oui, mais comme on le supprime pas vraiment je considéré que c'était seulement une modification de deux attributs delete et content (car on supprime le contenu en même temps que le tag deleted) et je respecté bien l'intérêt d'un DELETE au sens REST.

Je vous laisse bien valider une dernière fois ce comportement et je ferai la modif.

2022-03-22 13:00 UTC, bouttier requested changes
Encore quelques commentaires … merci !

2022-03-22 13:07 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +def create_report():
Après discussion, on a décidé de garder cela comme ça (permission du module SYNTHESE), en supposant que l’utilisateur a forcément des permissions au moins équivalente sur le module SYNTHESE.
On cherchera dans une future version de GeoNature à clarifier quelle est la permission donnant accès aux observations plutôt que l’approche par module actuelle qui amène à ce genre de soucis.

2022-03-22 13:12 UTC, Gaetanbrl commented on frontend/src/app/shared/discussionCardModule/discussion-card.component.ts
> +    const params = `idSynthese=${this.idSynthese}&type=1&sort=${this.sort}`;
du coup faut modifier toute le code et se baser sur le nom et pas l'id...

2022-03-22 13:14 UTC, bouttier commented on frontend/src/app/shared/discussionCardModule/discussion-card.component.ts
> +    const params = `idSynthese=${this.idSynthese}&type=1&sort=${this.sort}`;
Oui … :-/
Sans doute "type" à rajouter dans le ``fields`` du ``as_dict`` pour accéder au nom.

2022-03-22 13:31 UTC, pierrejego commented on backend/geonature/migrations/versions/095da7bc6667_add_table_gn_synthese_bib_reports_types.py
> +        (3, 'pin')
La non plus je comprends pas trop,  tu veux faire une jointure sur le champ varchar type directement ?

2022-03-22 13:33 UTC, pierrejego commented on backend/geonature/migrations/versions/095da7bc6667_add_table_gn_synthese_bib_reports_types.py
> +        (3, 'pin')
ok j'avais pas vu les commentaires en dessous

2022-03-22 13:37 UTC, pierrejego commented
@bouttier allez c'est la dernière cette fois  :)

2022-03-22 13:40 UTC, Gaetanbrl commented on backend/geonature/core/gn_synthese/routes.py
> +            raise BadRequest('This report type does not exist')
Fait

2022-03-22 13:45 UTC, bouttier commented on backend/geonature/migrations/versions/095da7bc6667_add_table_gn_synthese_bib_reports_types.py
> +        type VARCHAR NOT NULL
En fait je trouvais pertinent de rajouter un ``UNIQUE`` sur la colonne ``type`` (en plus du ``NOT NULL``). Mais ta remarque sur la ``PRIMARY KEY`` m’amène à me dire qu’en effet, on pourrait avoir que la colonne ``type`` qui soit la ``PRIMARY_KEY``. Du coup dans la table ``t_reports``, on aurait directement le ``type`` en ``VARCHAR``, et donc pas besoin de jointure pour utiliser les codes plutôt que les ID. La FK serait là juste pour garantir une valeur valide.

Mais ça marche aussi très bien comme ça donc je veux pas vous faire changer tout ça. Je vous laisse voir si ça vous arrange pour l’histoire des codes plutôt que les ID mais j’accepte les deux solutions sans soucis.

2022-03-22 14:16 UTC, Gaetanbrl commented on backend/geonature/migrations/versions/095da7bc6667_add_table_gn_synthese_bib_reports_types.py
> +        type VARCHAR NOT NULL
On va conserver ce fonctionnement relationnel actuel avec 2 tables vu que c'était déjà une modification demandé en début de revue  https://github.com/PnX-SI/GeoNature/pull/1774#discussion_r828913577 à la différence qu'on utilise maintenant un id auto incrémenté qu'on utilisera jamais pour utiliser le nom du type à la place si besoin.

2022-03-22 18:08 UTC, Gaetanbrl commented on backend/geonature/core/gn_synthese/routes.py
> +def create_report():
Très bien merci.

2022-03-23 08:20 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +    row = session.query(TReport).filter_by(id_report=data["idReport"], id_role=g.current_user.id_role)
Ligne à supprimer.

2022-03-23 08:20 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +    session.commit()
Il manque ``row.content = data["content"]`` avant le commit.

2022-03-23 08:20 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +    type_exists = BibReportsTypes.query.get_or_404(reportItem.id_type)
Ligne à supprimer.

2022-03-23 08:20 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +    if type_exists.type == "discussion":
``if reportItem.report_type.type == "discussion":``

2022-03-23 08:20 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +        print(reportItem.id_role)
``print`` à supprimer

2022-03-23 08:20 UTC, bouttier commented on backend/geonature/tests/fixtures.py
> +def bib_report_types_data():
Cette fixture me semble superflu, les types sont censé exister puisque créé par la migration.

2022-03-23 08:23 UTC, Gaetanbrl commented on backend/geonature/core/gn_synthese/routes.py
> +        print(reportItem.id_role)
oui ce n'est pas fini, j'ai un test à fix. J'aller nettoyer après ;)

2022-03-23 08:26 UTC, Gaetanbrl commented on backend/geonature/tests/fixtures.py
> +def bib_report_types_data():
je laisse les tests en l'état si fonctionnels. Merci.

2022-03-23 08:46 UTC, Gaetanbrl commented on backend/geonature/core/gn_synthese/routes.py
> +    session.commit()
Route plus utilisé (utilisation de DELETE maintenant) mais pourra servir pour les deux autres issues (signalement, épingle).
Je rajoute merci.

2022-03-23 10:51 UTC, bouttier approved these changes
Super, merci !

2022-03-23 11:00 UTC, merged