Feat: add areas view for synthese module
PnX-SI/GeoNature pull request #1881
Opened 2022-05-09 14:09 UTC by ch-cbna

See #1878

2022-11-28 16:13 UTC, TheoLechemia commented
On a refait un tour de l'aggrégation des géométrie : 
- On est obligé de faire un group by sur le geojson (car il est dans le select de la requête finale). On pourrait grouper sur la géométrie dans la 1ere CTE (qui récupère toute les obs), mais cela fausserait le paramètre "limit" qui serait basé sur le nombre distinct de géométrie et non plus sur le nombre d'obs au total. 
Avec le group by sur la geometrie, pour 100 000 obs on gagne uniquement 1 seconde (9s au lieu de 10s)
- sur le fait de construire directement la feature collection depuis la requête SQL, le problème vient du fait que la colonne "geojson_4326" est déjà une "string" et que de refaire un `json_build_object` sur celle-ci entraine une double sérialisation -> ` {"geom" : "{\"type\":\"Point\",\"coordinates\":[6.5,44.85]}"}`
- NB: faire un `json_build_object` sur une colonne de type géométrique entraîne magiquement sa transformation en geojson ! On aurait pu donc utiliser cette solution pour grouper par géometrie, mais on ne dispose pas de la géométrie en 4326 dans le référentiel géographique. Cela nécessiterai donc un reprojection assez coûteuse.

2022-11-28 20:10 UTC, bouttier commented
Plutôt que de re-projeter la geom 2154, ``func.ST_GeomFromGeoJSON(LAreas.geojson_4326)`` pour si zonages activé, directement ``the_geom_4326`` dans le cas contraire, et du coup group_by sur la geom et build complet en SQL.
Ça le ferait ? Je vous laisse juger si l’enjeu en vaut la chandelle …
Un peu bête de faire geojson → geom → geojson, mais pas pire que maintenant où on fait la déjsonification / jsonification en python …

2022-11-29 11:33 UTC, TheoLechemia commented
Du coup petit retour du test `func.ST_GeomFromGeoJSON(LAreas.geojson_4326)`
avec la requête suivante : 

```
SELECT
	json_build_object('type', 'FeatureCollection', 'features', json_agg(feature_subquery.feature)) AS DATA
FROM
	(
	SELECT
		json_build_object('geometry', ST_GeomFromGeoJSON(ref_geo.l_areas.geojson_4326), 'properties', json_build_object('observations', json_agg(json_build_object('id', gn_synthese.v_synthese_for_web_app.id_synthese, 'date_min', gn_synthese.v_synthese_for_web_app.date_min, 'lb_nom', gn_synthese.v_synthese_for_web_app.lb_nom, 'cd_nom', gn_synthese.v_synthese_for_web_app.cd_nom, 'observers', gn_synthese.v_synthese_for_web_app.observers, 'dataset_name', gn_synthese.v_synthese_for_web_app.dataset_name, 'url_source', gn_synthese.v_synthese_for_web_app.url_source, 'unique_id_sinp', gn_synthese.v_synthese_for_web_app.unique_id_sinp, 'nom_vern_or_lb_nom', COALESCE(NULLIF(gn_synthese.v_synthese_for_web_app.nom_vern, ), gn_synthese.v_synthese_for_web_app.lb_nom), 'count_min_max', CASE WHEN (gn_synthese.v_synthese_for_web_app.count_min != gn_synthese.v_synthese_for_web_app.count_max) THEN concat(gn_synthese.v_synthese_for_web_app.count_min, ' - ', gn_synthese.v_synthese_for_web_app.count_max) WHEN (gn_synthese.v_synthese_for_web_app.count_min IS NOT NULL) THEN concat(gn_synthese.v_synthese_for_web_app.count_min) ELSE END, 'entity_source_pk_value', gn_synthese.v_synthese_for_web_app.entity_source_pk_value)))) AS feature
	FROM
		gn_synthese.v_synthese_for_web_app
	JOIN gn_synthese.cor_area_synthese AS cor_area_synthese_1 ON
		gn_synthese.v_synthese_for_web_app.id_synthese = cor_area_synthese_1.id_synthese
	JOIN ref_geo.l_areas ON
		cor_area_synthese_1.id_area = ref_geo.l_areas.id_area
	JOIN ref_geo.bib_areas_types ON
		ref_geo.l_areas.id_type = ref_geo.bib_areas_types.id_type
	WHERE
		ref_geo.bib_areas_types.type_code = 'M10'
	GROUP BY
		ST_GeomFromGeoJSON(ref_geo.l_areas.geojson_4326) LIMIT 100000) AS feature_subquery
```
- on est à 25 secondes en mode maille avec 100000 données (contre 7 en utilisant le geojson précalculé et la double déjsonification / jsonification)
- on passe à 20 sec si on  `GROUP BY ref_geo.l_areas.geojson_4326` au lieu de `ST_GeomFromGeoJSON(ref_geo.l_areas.geojson_4326)`
- et à 18 seconde en utilisant directement la geom en 2154 (sans `ST_GeomFromGeoJSON` - juste pour test car non opérationnel d'avoir le geojson en 2154)
-> conclusion il faut mieux déserialisé pour reserialisé plutôt que de fait un `json_build_object('geometry', geom` qui a l'air assez peu performant.

2022-12-08 13:22 UTC, bouttier commented
Le groupement des observations pose problème avec la carte des dernières observations sur la page d’accueil. Lorsque l’on clique sur une observation, la modale d’affichage des observations n’arrive pas à afficher les informations puisque les properties sont désormais une liste de properties.

Cependant, il me semble compliqué d’afficher dans une modale les informations de plusieurs observations. Je pense donc qu’il faudrait que la page d’accueil récupère les observations sans groupement (on en récupère que 100, il ne doit pas y avoir de problème de perf) et qu’on active le groupage leaflet permettant de sélectionner une observation quand il y en a plusieurs au même endroit.

Quand à OccTax, lorsqu’il y a plusieurs relevées au même endroit, on peut uniquement sélectionner le relevé du dessus. Il serait sans doute pas mal d’activer à minima le groupage leaflet.

2022-12-13 08:23 UTC, bouttier requested changes
Que se passe-t-il si on appelle avec ``with_areas=1`` **et** ``ungrouped_geom=1`` ?

2022-12-13 08:23 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +        and (filters["with_areas"] in ["1", "true"] or filters["with_areas"] == True)
```suggestion
        and filters["with_areas"] in ["1", "true", True]
```

2022-12-13 08:23 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +        and (filters["ungrouped_geom"] in ["1", "true"] or filters["ungrouped_geom"] == True)
```suggestion
        and filters["ungrouped_geom"] in ["1", "true", True]
```

2022-12-13 08:29 UTC, bouttier commented
Pour simplifier, je dirais supprimer les paramètres ``with_areas`` et ``ungrouped_geom`` et les remplacer un par un unique paramètre ``format`` qui pourra valoir ``grouped`` ou ``areas``. Si non fourni, alors on renvoi la réponse normal (i.e. ungrouped).

2022-12-22 15:37 UTC, merged