Occtax dataset4
PnX-SI/GeoNature pull request #2078
Opened 2022-10-19 13:55 UTC by TheoLechemia

PR pour rendre possible la duplication d'occtax

2022-10-19 16:02 UTC, bouttier requested changes
Bravo pour le boulot !

2022-10-19 16:02 UTC, bouttier commented on frontend/cypress/integration/occtax-dataset-submodule-spec.js
> +  cy.intercept('http://127.0.0.1:8000/occtax/OCCTAX_DS/releves?**').as('getReleves');
Utiliser baseUrl ?

2022-10-20 08:31 UTC, TheoLechemia commented on frontend/cypress/integration/occtax-dataset-submodule-spec.js
> +  cy.intercept('http://127.0.0.1:8000/occtax/OCCTAX_DS/releves?**').as('getReleves');
Le backend n'est pas necessairement sur la même URL que le front. Plutôt mettre un paramètre pour l'URL du backend ?

2022-10-21 07:42 UTC, camillemonchicourt approved these changes

2022-10-21 09:15 UTC, TheoLechemia commented on frontend/cypress/integration/occtax-dataset-submodule-spec.js
> +  cy.intercept('http://127.0.0.1:8000/occtax/OCCTAX_DS/releves?**').as('getReleves');
Fait via le fichier cypress plugin qui permet d'éditer la conf cypress

2022-10-24 07:17 UTC, merged