Filtrer les métadonnées par zonage
PnX-SI/GeoNature pull request #2124
Opened 2022-11-10 08:41 UTC by Gaetanbrl

ref #1768 

> Cette PR a été commandité par le [MNHN](https://www.mnhn.fr/fr).

> Merci à @camillemonchicourt  @bouttier @TheoLechemia pour le support technique et la réactivité

## Description

Cette PR  permet de pouvoir filtrer les CA ou les JDD par zonage, notamment par région ou département.

Les développements avaient pour objectif que ce filtre supplémentaire fonctionne comme les autres : tous les JDD des CA retournés.

La PR pourra être mergée après la totale réalisation de ces tâches : 
- [x] développements (voir issue #1768 pour les détails)
- [x] Mise à jour de la branche avec develop (Rebase)
- [x] Respect du code style
- [ ] Revue technique et fonctionnelle
- [x] Cypress frontend test
- [x] Pytest backend test
- [x] Documentation => `default_config.toml.example`

2022-11-10 10:20 UTC, Gaetanbrl commented on backend/geonature/utils/config_schema.py
> +        fields.Dict, load_default=[{"label": "Communes", "type_code": "COM"}]
> Si ils sont bien présents dans tous les GeoNature par défaut

Dans l'install par défaut on les a bien en tout cas.

2022-11-10 11:27 UTC, bouttier requested changes
Pas encore testé mais quelques premiers retours, notamment sur les évolutions de la route du backend.

2022-11-10 11:27 UTC, bouttier commented on backend/geonature/core/gn_meta/routes.py
> +# from geonature.core.ref_geo.models import BibAreasTypes, LiMunicipalities, LAreas
```suggestion
```

2022-11-10 11:27 UTC, bouttier commented on backend/geonature/core/gn_meta/routes.py
> +        af_list = af_list.filter_by_params(request.json)
Rétablir le reste de la fonction telle qu’elle était originalement. Garder uniquement cette partie.

2022-11-10 11:27 UTC, bouttier commented on frontend/src/app/GN2CommonModule/form/data-form.service.ts
> +      `${AppConfig.API_ENDPOINT}/geo/areas?area_name=${area_name}&id_type=${id_type}`
Peut-on passer plutôt le ``type_code`` (argument ``area_type`` au niveau de l’API) ?

2022-11-10 11:27 UTC, bouttier commented on frontend/src/app/GN2CommonModule/form/data-form.service.ts
>    getAcquisitionFrameworksList(searchTerms = {}) {
Il faut passer également les paramètres GET pour pouvoir activer la récupération des JDD (``datasets=1``, …)

2022-11-10 11:27 UTC, bouttier commented on frontend/src/app/syntheseModule/synthese.component.ts
> +        initialFilter['limit'] = 6000;
```suggestion
```

2022-11-10 12:29 UTC, Gaetanbrl commented on frontend/src/app/GN2CommonModule/form/data-form.service.ts
>    getAcquisitionFrameworksList(searchTerms = {}) {
> Pas encore testé mais quelques premiers retours, notamment sur les évolutions de la route du backend.

J'étais justement en train de faire les modifs.

2022-11-10 12:30 UTC, Gaetanbrl commented on frontend/src/app/syntheseModule/synthese.component.ts
> +        initialFilter['limit'] = 6000;
oups...

2022-11-10 12:37 UTC, Gaetanbrl commented on frontend/src/app/GN2CommonModule/form/data-form.service.ts
> +      `${AppConfig.API_ENDPOINT}/geo/areas?area_name=${area_name}&id_type=${id_type}`
Oui, c'est mieux et prévu dans la route GET /areas : 

```
    if "type_code" in params:
        q = q.filter(LAreas.area_type.has(BibAreasTypes.type_code.in_(params["type_code"])))
```

2022-11-10 12:50 UTC, Gaetanbrl commented on backend/geonature/core/gn_meta/routes.py
> +        af_list = af_list.filter_by_params(request.json)
ca devrait être bon à présent.

2022-11-10 15:57 UTC, bouttier requested changes
Il faut que je prenne un peu le temps de tester mais on me semble très proche du but ! Merci !

2022-11-10 16:18 UTC, Gaetanbrl commented on backend/geonature/core/gn_meta/models.py
> +        areas = params.pop("area") if "area" in params else None
https://github.com/PnX-SI/GeoNature/pull/2124/commits/024f8f298a6c3024cc9dfebdfe949812c2ddf543

2022-11-16 09:44 UTC, Gaetanbrl commented
@bouttier en parallèle des travaux en cours sur la séparation backend (docker) / frontend , quelles sont les risques de conflit avec cette PR ?

2022-11-16 17:58 UTC, bouttier commented
Il n’y a pas d’impact particulier de la séparation frontend / backend sur cette PR.

Potentiel conflit : #2027, prévu d’intégrer en 2.11 également

2022-11-23 10:23 UTC, bouttier requested changes
Les 2 points restant pour pouvoir merger cette PR sont :
- la séparation des termes de recherche envoyés en POST des sélecteurs envoyés en GET
- un cas de test sur une recherche géographique, où on vérifie qu’elle fonctionne correctement

2022-11-23 10:23 UTC, bouttier commented on frontend/src/app/GN2CommonModule/form/data-form.service.ts
>    getAcquisitionFrameworksList(searchTerms = {}) {
Pas de construction manuel des paramètres GET, ``{params: params}`` sert à ça.

2022-11-23 10:23 UTC, bouttier commented on frontend/src/app/GN2CommonModule/form/data-form.service.ts
>    getAcquisitionFrameworksList(searchTerms = {}) {
Cela veut certainement reprendre la fonction ``getMetadata`` pour distinguer les ``searchTerms`` reçu en paramètre des paramètres GET ``datasets=1``, ``creator=1`` et ``actors=1``.

2022-11-28 11:29 UTC, Gaetanbrl commented on backend/geonature/tests/test_gn_meta.py
> +        # POST EMPTY REQUEST FAIL WITHOUT ANY PARAMS
c'est pas ce que fait le test précédent ?
https://github.com/jdev-org/GeoNature/blob/issue-1768/backend/geonature/tests/test_gn_meta.py#L216

2022-11-28 11:30 UTC, Gaetanbrl commented on backend/geonature/tests/test_gn_meta.py
> +        # POST EMPTY REQUEST FAIL WITHOUT ANY PARAMS
Je n'ai pas vu l'intérêt de le remettre dans ce test vu que ca cible la même route

2022-11-28 11:31 UTC, Gaetanbrl commented on frontend/src/app/GN2CommonModule/form/data-form.service.ts
>    getAcquisitionFrameworksList(searchTerms = {}) {
C'était pour ne pas ajouter de paramètres inutiles dans l'appel GET.

2022-11-28 11:32 UTC, bouttier commented on backend/geonature/tests/test_gn_meta.py
> +        # POST EMPTY REQUEST FAIL WITHOUT ANY PARAMS
En effet !

2022-11-28 11:41 UTC, Gaetanbrl commented on frontend/src/app/GN2CommonModule/form/data-form.service.ts
>    getAcquisitionFrameworksList(searchTerms = {}) {
Je viens de pousser la modif pour utiliser une boucle qui va créer les `HttpParams`.

Je n'irai pas plus loin pour `autocompleteRefGeo`  étant donné que c'est un Bonus dans la PR qui ne sert nul part. Je l'avais fait avant qu'on réutilise le composant de sélection des entités.

2022-11-28 11:42 UTC, Gaetanbrl commented on frontend/src/app/GN2CommonModule/form/data-form.service.ts
>    getAcquisitionFrameworksList(searchTerms = {}) {
idem `getAreasTypes` n'est pas utilisé.

2022-11-28 11:44 UTC, Gaetanbrl commented on backend/geonature/tests/test_gn_meta.py
> +        assert response.status_code == 400
changé !

2022-11-28 11:44 UTC, Gaetanbrl commented on backend/geonature/tests/test_gn_meta.py
> +        response = self.client.post(
changé !

2022-11-28 11:44 UTC, Gaetanbrl commented on backend/geonature/core/gn_meta/models.py
> +    def filter_by_areas(self, areas):
couvert !

2022-11-28 11:45 UTC, Gaetanbrl commented on backend/geonature/core/gn_meta/models.py
> +        if areas and areas is not None:
changé !

2022-11-28 12:49 UTC, bouttier commented on frontend/src/app/GN2CommonModule/form/data-form.service.ts
> +    return this._http.post<any>(`${AppConfig.API_ENDPOINT}/meta/acquisition_frameworks?`, params, {
```suggestion
    return this._http.post<any>(`${AppConfig.API_ENDPOINT}/meta/acquisition_frameworks`, params, {
```

2022-11-29 09:03 UTC, Gaetanbrl commented
1 demande supplémentaire faite par @bouttier :

Ajouter un test pour valider que les CA retournés sont bien ceux concernés par le filtre par zone : 

> il manque vraiment un test fonctionnel qui vérifie que la recherche géographique fonctionne.

2022-11-29 13:57 UTC, Gaetanbrl commented
pytest semble échouer sur le test suivant : 

> test_delete_dataset

backend/geonature/tests/test_gn_meta.py:579: AssertionError

```
E       assert 204 == 409
E        +  where 204 = <WrapperTestResponse streamed [204 NO CONTENT]>.status_code
E        +  and   409 = Conflict.code
```

2022-11-30 09:40 UTC, Gaetanbrl commented on backend/geonature/tests/test_gn_meta.py
> +    return communeMatch
tu veux dire ? : 

`    areas = relationship(LAreas, secondary=corAreaSynthese, backref="synthese_obs")`

A la place de 

`areas = relationship(LAreas, secondary=corAreaSynthese, db.backref("synthese_obs"))`

2022-11-30 09:59 UTC, Gaetanbrl commented
@bouttier @camillemonchicourt malheureusement je n'ai plus de temps à consacrer sur cette PR pour me pencher sur la dernière revue d'Elie (optimisations du test).

Le dernier test rajouté permet de valider que le filtre par zone ne retourne pas le CA d'une autre zone. On répond en ce sens à l'avant dernière revue.

Donc sauf disfonctionnement / régression constaté je ne ferai pas de modifications supplémentaires de type "optimisation".

Merci pour le temps passé pour les revues.

2022-11-30 17:32 UTC, merged