Feat Synthese: add status, red lists filters
PnX-SI/GeoNature pull request #2173
Opened 2022-11-28 11:01 UTC by amandine-sahl

Test squash

Resolve #1492.

Feat frontend/synthese: improve display of form fields used

Resolve #1492.

Feat frontend/synthese: put taxonomic rank fields in a section

Resolve #1492.

Fix backend: restore correct order for CorAreaSynthese

Fix backend/migrations: move bdc status link db upgrade to head of geonature branch

Fix frontend: fix merge errors

Fix frontend: change red_lists ws name to status_values

Fix frontend/synthese-advanced: dynamic tree now avalaible in ngOnInit

Fix frontend/synthese: change fields names

Feat backend: replace CorAreaStatus by TaxrefBdcStatutCorTextArea

Fix frontend/synthese: use correct field names and css class

Refactor backend: replace TaxrefBdcStatutCorTextArea by bdc_statut_cor_text_area

Correction rebase

Black

Correction rebase

Remove console.log

Remove unused import

Add basic tests

Refactor frontend/synthese-form: format source code

Install departements before taxref

2022-11-28 20:58 UTC, amandine-sahl commented
Remplace les pulls requests (qui sont à fermer sans merge) : 
* #1535
* #1536 
* #1537 
* #1538

2022-11-29 08:29 UTC, bouttier requested changes
J’ai l’impression qu’on ajoute beaucoup de jointures, je me demande l’impact sur les performances de la synthèse ? Est-ce qu’il est toujours nécessaire de récupérer toutes ces informations ? Elles figurent toutes dans la liste des observations ?

Par ailleurs, on refait les jointures dans ``SyntheseQuery`` pour pouvoir filtrer ; est-ce que la BDCS se retrouve jointe 2 fois ? Il me semble qu’il y a du code qui vise à éviter de rejoindre lorsque déjà join mais est-ce qu’il est mis en œuvre ici ? L’utilisation de l’ORM simplifierait ceci mais c’est un autre sujet !

2022-11-29 08:29 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +        filters = json.loads(request.data.decode("utf-8"))
On support Python ≥ 3.7, si ce bloque sert à 3.5, inutile de le rajouter.

2022-11-29 08:29 UTC, bouttier commented on backend/geonature/utils/config_schema.py
> +    ID_SEARCH_OBSERVER_LIST = fields.Integer(load_default=1)
Utiliser le ``code_liste`` plutôt que l’``id_liste`` !

2022-11-29 08:29 UTC, bouttier commented on backend/geonature/utils/config_schema.py
> +    SEARCH_OBSERVER_WITH_LIST = fields.Boolean(load_default=False)
Comme ceci peut-être ?
```suggestion
    SEARCH_OBSERVER_FREE_TEXT = fields.Boolean(load_default=False)
```

2022-11-29 08:29 UTC, bouttier commented on backend/geonature/utils/config_schema.py
> +    CRUVED_SEARCH_WITH_OBSERVER_AS_TXT = fields.Boolean(load_default=False)
Je pensais qu’on avait supprimé ce paramètre. Dans tous les cas, je ne vois pas où il est utilisé.

2022-11-29 08:29 UTC, bouttier commented on backend/geonature/utils/config_schema.py
> +    TAXON_RESULT_NUMBER = fields.Integer(load_default=20)
Est-ce que ça serait pas plus parlant ?
```suggestion
    TAXON_AUTOCOMPLETE_ITEMS_COUNT = fields.Integer(load_default=20)
```

2022-11-29 08:30 UTC, amandine-sahl commented on backend/geonature/core/gn_synthese/routes.py
> +        filters = json.loads(request.data.decode("utf-8"))
En fait si on supprime ça, on ne récupère plus les geointersections

2022-11-29 08:37 UTC, jpm-cbna commented on backend/geonature/utils/config_schema.py
> +    ID_SEARCH_OBSERVER_LIST = fields.Integer(load_default=1)
Apparemment, il y a eu un problème avec le _rebasage_ dans ce fichier. Je regarde pour ne garder que les modifications liées aux nouveaux paramètres.

2022-11-29 11:10 UTC, jpm-cbna commented on backend/geonature/utils/config_schema.py
> +    ID_SEARCH_OBSERVER_LIST = fields.Integer(load_default=1)
Voilà, je viens de repousser une version où j'ai supprimé les paramètres que l'on avait rajouté par erreur.

Attention, dans ce fichier, je n'ai fait que réarranger les paramètres de la section SYNTHESE pour y voir plus clair. Je n'ai pas jouté le paramètre `ID_SEARCH_OBSERVER_LIST`, il existait déjà, je l'ai juste déplacé.

2022-11-29 11:11 UTC, jpm-cbna commented on backend/geonature/utils/config_schema.py
> +    SEARCH_OBSERVER_WITH_LIST = fields.Boolean(load_default=False)
Idem, le paramètre `SEARCH_OBSERVER_WITH_LIST` est un paramètre existant qui a juste été déplacé.

2022-11-29 11:11 UTC, jpm-cbna commented on backend/geonature/utils/config_schema.py
> +    CRUVED_SEARCH_WITH_OBSERVER_AS_TXT = fields.Boolean(load_default=False)
`CRUVED_SEARCH_WITH_OBSERVER_AS_TXT` était effectivement un paramètre à supprimé. C'est fait.

2022-11-29 11:12 UTC, jpm-cbna commented on backend/geonature/utils/config_schema.py
> +    TAXON_RESULT_NUMBER = fields.Integer(load_default=20)
> Est-ce que ça serait pas plus parlant ?

Ici aussi le paramètre `TAXON_RESULT_NUMBER` est un paramètre existant qui a juste été déplacé.

2022-11-29 11:26 UTC, jpm-cbna commented
> J’ai l’impression qu’on ajoute beaucoup de jointures, je me demande l’impact sur les performances de la synthèse ? Est-ce qu’il est toujours nécessaire de récupérer toutes ces informations ? Elles figurent toutes dans la liste des observations ?
> 
> Par ailleurs, on refait les jointures dans `SyntheseQuery` pour pouvoir filtrer ; est-ce que la BDCS se retrouve jointe 2 fois ?

Alors, j'ai pas mal travaillé les performances et l'on arrive à quelque chose de fonctionnel même sur plusieurs millions de données.
Mais effectivement, cela rajoute des jointures car nous sommes obligé à la fois d'aller vérifier que le taxon de l'observation et bien lié aux textes de protection choisi mais aussi que l'observation est bien lié à la zone géographique d'application du texte...
Et pour éviter la collision avec les tables du `ref_geo` liés aux filtres géographiques de la Synthese (communes, départements...), nous sommes obligé d'utilisé des alias.

Je ne pense pas que la BDC soit lié plusieurs fois.

2022-11-30 13:21 UTC, bouttier commented on backend/geonature/core/gn_synthese/routes.py
> +        filters = json.loads(request.data.decode("utf-8"))
Le problème est ici :
https://github.com/PnX-SI/GeoNature/blob/2.10.3/frontend/src/app/GN2CommonModule/form/synthese-form/synthese-data.service.ts#L147
Cette ligne modifie le header ``Content-Type`` en fonction du format de la réponse attendu, mais c’est une confusion entre le format de la requête et le format de la réponse. Ici on modifie le header ``Content-Type`` de la requête, et en conséquence ``request.is_json`` passe à ``False`` mais c’est une erreur car la requête est bien en JSON. On a pas le contrôle sur le header ``Content-Type`` de la réponse côté front car celui-ci est mis par le backend !
Bref, la ligne ``headers: …`` est à supprimer et le bloque ``elif request.data`` pourra être supprimé également sans soucis.

2022-12-02 15:31 UTC, jpm-cbna commented on backend/geonature/core/gn_synthese/routes.py
> +        filters = json.loads(request.data.decode("utf-8"))
Voilà, c'est corrigé dans le dernier commit.

2022-12-05 19:46 UTC, merged