feat(api): add notification for comment on obs
PnX-SI/GeoNature pull request #2461
Opened 2023-04-06 18:24 UTC by mvergez

Ajout d'une notification lorsqu'un commentaire est ajouté sur l'observation d'un utilisateur.
La notification n'est pas envoyé aux utilisateurs commentant une observation qui n'ont pas faite.

**Code de la notification :** VALIDATION-NEW-COMMENT
**Template de mail :**
```html
<p>Bonjour <i>{{ role.nom_complet }}</i> !</p> 
<p>Votre observation de l'espèce : {{ synthese.nom_cite }} du {{ synthese.meta_create_date.strftime('%d-%m-%Y') }} a reçu un commentaire</p>
<p>Vous pouvez y accéder directement <a href="{{ url }}">ici</a></p>
<p><i>Vous recevez cet email automatiquement via le service de notification de GeoNature.</i></p>
```

**Template de notification :** 
```html
Vous avez reçu un nouveau commentaire sur votre observation de {{ synthese.nom_cite }} du {{ synthese.meta_create_date.strftime('%d-%m-%Y') }}
```

Closes #2460

2023-04-06 18:36 UTC, camillemonchicourt commented
Je pense qu'il faut renommer la notification OBSERVATION-COMMENT car ce n'est pas spécialement lié à la validation.

Et ça me semble un peu partiel si celui qui commente n'est pas notifié en cas de réponse.

2023-04-07 06:30 UTC, camillemonchicourt commented on backend/geonature/core/gn_synthese/routes.py
> +            + "/#/validation/occurrence/"
Le lien de la notification ne doit pas renvoyer sur la fiche de l'observation dans le module VALIDATION, mais dans le module SYNTHESE.
Car la plupart des observateurs n'ont pas les droits d'accès au module Validation, donc le lien ne fonctionnera pas.

2023-04-07 06:32 UTC, camillemonchicourt commented on backend/geonature/migrations/versions/95acee9f0452_add_validation_comment_notification.py
> +            "Se déclenche lorsqu'un nouveau commentaire "
Plutôt indiquer : "Se déclenche lorsqu'un nouveau commentaire est ajouté sur une de vos observations"

2023-04-07 06:33 UTC, camillemonchicourt commented on backend/geonature/migrations/versions/95acee9f0452_add_validation_comment_notification.py
> +        label="Nouveau commentaire dans une discussion sur une observation",
Raccourcir en "Nouveau commentaire sur une observation" ?

2023-04-07 07:11 UTC, DonovanMaillard commented
> Je pense qu'il faut renommer la notification OBSERVATION-COMMENT car ce n'est pas spécialement lié à la validation.
> 
> Et ça me semble un peu partiel si celui qui commente n'est pas notifié en cas de réponse.

Oui, en toute logique, il faut notifier le digitiser + tous ceux qui ont contribué aux commentaires sur l'observation en question, pour faciliter les échanges

2023-04-07 07:16 UTC, DonovanMaillard commented
> Vous avez reçu un nouveau commentaire sur votre observation de {{ synthese.nom_cite }} du {{ synthese.meta_create_date.strftime('%d-%m-%Y') }}

C'est assez ambigu comme message. Soit c'est "votre observation de [nom cité] du + date_début, soit c'est votre observation saisie le ... 

Je privilégierais la 1ère option, et je sais pas si ca serait pas intéressant de remettre aussi la commune pour mieux resituer la donnée en question. Idem, ca peut etre intéressant dans la notification de savoir de qui vient le commentaire. 

> [Tel utilisateur] a commenté votre observation de {{ synthese.nom_cite }} du {{ synthese.date_min.strftime('%d-%m-%Y') à [la ou les communes] }}

2023-04-07 07:36 UTC, mvergez commented
Salut @DonovanMaillard !

Merci beaucoup pour tous tes retours !

> Oui, en toute logique, il faut notifier le digitiser + tous ceux qui ont contribué aux commentaires sur l'observation en question, pour faciliter les échanges

Oui je suis d'accord, mais je pense que ça doit être fait en 2 temps. Car en regardant un peu le code il faudrait, à chaque POST de commentaire, faire un requête pour accéder à tous les commentaires de l'observation. Cela peut-être un peu lourd... Il faudrait je pense réfléchir à un meilleur moyen. Via peut-être le frontend qui récupère déjà tous les commentaires... A réfléchir mais ce n'est pas l'objectif de la PR et la demande formulée, donc à faire dans une autre PR à mon sens.

> C'est assez ambigu comme message. Soit c'est "votre observation de [nom cité] du + date_début, soit c'est votre observation saisie le ...

Je crois que j'ai mal compris ta remarque puisqu'au final on partirait sur : **[Tel utilisateur] a commenté votre observation de {{ synthese.nom_cite }} du {{ synthese.date_min.strftime('%d-%m-%Y')**. Ce qui est assez similaire à ce que j'avais proposé non ?

Pour la commune, bonne idée aussi mais cela fait rajouter une jointure à la query, est-ce nécessaire ? Beaucoup d'observations à la même date peuvent-elles être dans 2 communes séparées ? Sachant qu'on entre un point précis ou une géométrie plutôt qu'une commune, donc on n'a pas forcément l'information si on n'a pas regardé notre observation a posteriori (par exemple si on saisit via occtax mobile) ?

Ok pourquoi pas pour l'utilisateur, je vais regarder ce qu'il est possible de faire.

Merci en tout cas pour tes suggestions !

2023-04-07 07:52 UTC, camillemonchicourt commented
Je rejoins @DonovanMaillard, la date de l'observation est mieux que la date de saisie, qui peuvent en effet être bien différents.
Pour l'ajout de la commune, c'est un plus mais pas essentiel selon moi. Ça permet de mieux identifier ce dont il s'agit dès réception de la notification.

2023-04-07 07:56 UTC, mvergez commented
Yes je suis d'accord aussi pour la date, du coup `date_min` ou `date_max` ?
C'est possible pour la commune mais la requête en vaut-elle la peine ? C'est pas grand chose c'est une jointure mais à voir

2023-04-07 08:02 UTC, mvergez commented on backend/geonature/migrations/versions/95acee9f0452_add_validation_comment_notification.py
> +        label="Nouveau commentaire dans une discussion sur une observation",
Corrigé dans https://github.com/PnX-SI/GeoNature/pull/2461/commits/c9f501d81b18688ec06239c79c9c40efb91243f5

2023-04-07 08:02 UTC, mvergez commented on backend/geonature/migrations/versions/95acee9f0452_add_validation_comment_notification.py
> +            "Se déclenche lorsqu'un nouveau commentaire "
Corrigé dans https://github.com/PnX-SI/GeoNature/pull/2461/commits/c9f501d81b18688ec06239c79c9c40efb91243f5

2023-04-07 08:02 UTC, mvergez commented on backend/geonature/core/gn_synthese/routes.py
> +            + "/#/validation/occurrence/"
Corrigé dans https://github.com/PnX-SI/GeoNature/pull/2461/commits/1f8851cd109775265519c35be9bcf33ccdcabcaa

2023-04-07 08:32 UTC, DonovanMaillard commented
> Je crois que j'ai mal compris ta remarque puisqu'au final on partirait sur : **[Tel utilisateur] a commenté votre observation de {{ synthese.nom_cite }} du {{ synthese.date_min.strftime('%d-%m-%Y')**.

C'est justement la date qui différait, j'avais pris date_min ;)  A mon sens date min, dans tous les cas on ne vas pas mettre les 2, et c'est souvent un jour + son lendemain pour des observations de nuit. Donc date_min reste pertinent je pense. 

Pour les communes si ca vient rajouter trop de jointures etc, c'est un plus mais pas indispensable donc ça justifie pas de ralentir et alourdir le mécanisme. Par contre récupérer tous les commentateurs d'une donnée me semble essentiel. 

A fait une donnée, B fait une remarque, A répond -> B n'est pas informé, ça laisse peu d'intérêt et je vois déjà les mails arriver pour me signaler un bug :)

2023-04-07 08:38 UTC, mvergez commented
Ok top merci @DonovanMaillard ! Je vais regarder pour les commentaires et réfléchir au meilleur moyen de le faire :) Je le proposerait dans cette PR

2023-04-07 13:35 UTC, camillemonchicourt commented
Suite aux différents échanges, @mvergez a élargi le périmètre fonctionnel de cette fonctionnalité et fait en sorte de notifier aussi les observateurs (sans doublonner si le digitiser est aussi observateur), mais aussi les commentateurs de l'observation : 

- Si "admin" fait une obs avec "agent" et que "validateur" commente : "agent" et "admin" sont prévenus
- Si "admin" rajoute un commentaire : "agent" et "validateur" sont prévenus

2023-04-07 13:43 UTC, DonovanMaillard commented
> Suite aux différents échanges, @mvergez a élargi le périmètre fonctionnel de cette fonctionnalité et fait en sorte de notifier aussi les observateurs (sans doublonner si le digitiser est aussi observateur), mais aussi les commentateurs de l'observation :
> 
>     * Si "admin" fait une obs avec "agent" et que "validateur" commente : "agent" et "admin" sont prévenus
> 
>     * Si "admin" rajoute un commentaire : "agent" et "validateur" sont prévenus

parfait, merci @mvergez :)

2023-04-11 12:34 UTC, camillemonchicourt reviewed
Révision des messages de notification, suite à l'ajout de la notification des commentateurs.

2023-04-11 12:34 UTC, camillemonchicourt commented on backend/geonature/migrations/versions/95acee9f0452_add_validation_comment_notification.py
> +            "Se déclenche lorsqu'un nouveau commentaire est ajouté à une de vos observations"
Suite aux évolutions de la PR, à renommer en 
"Se déclenche lorsqu'un nouveau commentaire est ajouté à une de vos observations, ou une observation que vous avez commenté"

2023-04-11 12:34 UTC, camillemonchicourt commented on backend/geonature/migrations/versions/95acee9f0452_add_validation_comment_notification.py
> +    email_content = """ <p>Bonjour <i>{{ role.nom_complet }}</i> !</p>
Suite aux évolutions de la PR, à renommer en 
```
email_content = """ <p>Bonjour <i>{{ role.nom_complet }}</i> !</p> 
    <p>{{ user.nom_complet }} a commenté l'observation de {{ synthese.nom_cite }} du {{ synthese.meta_create_date.strftime('%d-%m-%Y') }} que vous avez créé ou commenté</p>
    <p>Vous pouvez y accéder directement <a href="{{ url }}">ici</a></p>
    <p><i>Vous recevez cet email automatiquement via le service de notification de GeoNature.</i></p>
    """
    ```

2023-04-11 12:34 UTC, camillemonchicourt commented on backend/geonature/migrations/versions/95acee9f0452_add_validation_comment_notification.py
> +    db_content = """ {{ user.nom_complet }} a commenté votre observation
Suite aux évolutions de la PR, à renommer en 
```
db_content = """ {{ user.nom_complet }} a commenté l'observation 
    de {{ synthese.nom_cite }} du {{ synthese.meta_create_date.strftime('%d-%m-%Y') }} que vous avez créé ou commenté
    ```

2023-04-11 13:46 UTC, mvergez commented on backend/geonature/migrations/versions/95acee9f0452_add_validation_comment_notification.py
> +    email_content = """ <p>Bonjour <i>{{ role.nom_complet }}</i> !</p>
Merci @camillemonchicourt ! Traité dans le commit https://github.com/PnX-SI/GeoNature/pull/2461/commits/8b629e89d3d09799fdbdd67f8db1c33f613dd37d

2023-04-11 13:54 UTC, mvergez commented on backend/geonature/migrations/versions/95acee9f0452_add_validation_comment_notification.py
> +            "Se déclenche lorsqu'un nouveau commentaire est ajouté à une de vos observations"
Changé dans https://github.com/PnX-SI/GeoNature/pull/2461/commits/55c4c22ed8b9345c100c5af82d4e393926845c01

2023-04-17 08:31 UTC, bouttier requested changes

2023-04-17 08:31 UTC, bouttier commented on backend/geonature/migrations/versions/95acee9f0452_add_comment_notification.py
> +)
Malheureusement, il ne faut pas utiliser les modèles dans les migrations Alembic.
En effet, s’ils venaient à évoluer, on se mettrait alors à utiliser des modèles qui correspondent à un état future de la base de données (par exemple une colonne qui n’existe pas encore au moment d’appliquer cette révision).

2023-04-17 10:55 UTC, mvergez commented on backend/geonature/core/gn_synthese/routes.py
> +        context={"synthese": synthese, "user": user, "content": content},
Je viens de faire le changement ici, que j'ai répercuté sur la migration

2023-04-17 10:55 UTC, mvergez commented on backend/geonature/migrations/versions/95acee9f0452_add_comment_notification.py
> +)
Ok, c'est fait. J'ai utilisé l'exemple que tu m'as donné ici : https://github.com/PnX-SI/gn_module_import/blob/master/backend/gn_module_import/migrations/0ff8fc0b4233_remove_archive_schema.py#L28

2023-05-15 13:10 UTC, camillemonchicourt approved these changes

2023-05-22 07:36 UTC, camillemonchicourt approved these changes

2023-05-22 16:07 UTC, bouttier approved these changes
Attention en mergeant à la révision alembic

2023-05-22 17:42 UTC, merged