register enhancement
PnX-SI/GeoNature pull request #2575
Opened 2023-05-31 12:36 UTC by joelclems

## Inscription
- [x] frontend message quand l'api d'inscription renvoie une erreur (identifiant existe deja, demande en cours)
- [x] message plus explicite quand on valide un utilisateur (pas de retour à la page d'accueil direct)
- [x] prise en compte de l'organisme (en texte) dans les champs additionels

2023-06-09 12:11 UTC, amandine-sahl requested changes
C'est peu être l'occasion de rajouter des tests

2023-06-09 12:11 UTC, amandine-sahl commented on backend/geonature/core/users/register_post_actions.py
> +    return (
Déjà une chaine de caractère ou une liste EmailStrOrListOfEmailStrField

2023-06-09 12:11 UTC, amandine-sahl commented on backend/geonature/core/users/register_post_actions.py
> +    # dans le cas ou on a plusieurs validateurs et on veut prévenir tout le monde
Faire un commentaire plus explicite et/ou faire une issue sur la question de la validation des comptes dans le contexte de plusieurs validateurs

2023-06-09 12:11 UTC, amandine-sahl commented on backend/geonature/core/users/templates/email_admin_validate_account.html
>    <li><b>Prénom :</b> {{user.prenom_role}}</li>
Voir si ce  n'est pas plus pertinent d'avoir un champ organisme basé sur bib_organisme + champ texte autre organisme

2023-06-09 12:11 UTC, amandine-sahl commented on frontend/src/app/modules/login/sign-up/sign-up.component.ts
> +      finalForm['champs_addi']['organisme'] = this.form.value['organisme'];
Enlever organisme des champs prédéfinis et le mettre dans les champs additionnels

2023-06-10 17:16 UTC, camillemonchicourt commented on backend/geonature/core/users/templates/email_admin_validate_account.html
>    <li><b>Prénom :</b> {{user.prenom_role}}</li>
Pour l'instant on reste sur un champs texte dans le formulaire de création de compte.
Mais oui, ça serait bien à terme.

2023-06-12 07:18 UTC, joelclems commented on frontend/src/app/modules/login/sign-up/sign-up.component.ts
> +      finalForm['champs_addi']['organisme'] = this.form.value['organisme'];
Les champs additionels sont optionnels et à définir dans la config

c'est pas mal au final de garder ce champs dans les champs prédéfinis

2023-06-12 07:26 UTC, camillemonchicourt commented on frontend/src/app/modules/login/sign-up/sign-up.component.ts
> +      finalForm['champs_addi']['organisme'] = this.form.value['organisme'];
Oui on peut se demander si au final on n'en fait pas juste un champs additionnel optionnel et que chacun se le met ou pas...
Mais c'est vrai aussi que c'est un champs classique qui est pertinent dans toute demande de création de compte, à priori.
Donc ça me va de le laisser de base.

2023-06-22 14:54 UTC, TheoLechemia approved these changes

2023-06-22 15:33 UTC, merged

2024-04-25 08:03 UTC, TheoLechemia commented
@jpm-cbna une erreur ?