[IMPORT][OCCHAB] Feat import/occhab id import
PnX-SI/GeoNature pull request #2932
Opened 2024-02-22 10:01 UTC by JulienCorny

2024-04-04 09:43 UTC, JulienCorny commented
- changement de position du bouton "voir les données dans le module de destination" : en haut du rapport
- mise en place du filtre sur les id_import dans occhab avec pnx-dynamic-form-generator
- prise en compte des commentaires précédents sur la PR

2024-08-14 16:51 UTC, bouttier requested changes
PR rebasé avec sans doute erreurs. Il y a quelques modifs à faire dans tous les cas.

2024-08-14 16:51 UTC, bouttier commented on backend/geonature/core/imports/routes/imports.py
> +@blueprint.route("/<destination>/imports/<int:import_id>/data_link", methods=["GET"])
Route à supprimer et à remplacer par une simple propriété sur le modèle d’import.

2024-08-14 16:51 UTC, bouttier commented on contrib/gn_module_occhab/backend/gn_module_occhab/imports/__init__.py
> +    return datalink
Pourquoi ne pas directement renvoyer une URL correctement formaté ? Le routeur angular n’est pas capable de distinguer les paramètres lui même ?

2024-08-14 16:51 UTC, bouttier commented on contrib/gn_module_occhab/frontend/app/components/occhab-map-list/occhab-map-list-filter.component.ts
> +        this.processedDefaultFilters = { id_import: [Number(params.get('id_import'))] };
Pas sûr de comprendre le rôle de processedDefaultFilters et pourquoi seul l’id_import est concerné ?

2024-08-14 16:51 UTC, bouttier commented on frontend/src/app/modules/imports/services/data.service.ts
> +  get_imported_data_link(id_import) {
À supprimer au profit d’une propriété sur l’import.

2024-08-14 16:51 UTC, bouttier commented on frontend/src/app/modules/imports/components/import_report/import_report.component.ts
> +  getImportedDataLink() {
À supprimer au profit d’une propriété sur l’import.

2024-08-14 16:51 UTC, bouttier commented on frontend/src/app/modules/imports/components/import_report/import_report.component.ts
> +    this.getImportedDataLink();
À supprimer.

2024-08-14 16:52 UTC, bouttier commented on contrib/gn_module_occhab/backend/gn_module_occhab/imports/__init__.py
> +    return datalink
À intégrer à OcchabImportMixin.

2024-10-01 14:28 UTC, jacquesfize commented
Closed and restart #3207

2024-10-01 14:28 UTC, jacquesfize commented
Closed and restart #3207

2024-10-01 14:28 UTC, closed without merging