[IMPORT] hide map imported data if null bbox
PnX-SI/GeoNature pull request #3007
Opened 2024-04-26 10:32 UTC by edelclaux

Travail réalisé par @VincentCauchois 

## Commit [5edcda5](https://github.com/PnX-SI/GeoNature/commit/5edcda544b8c2936e91de7e016de763205b82814) - fix(import): modify get_valid_bbox to support done imports

Modify the function get_valid_bbox, from imports utils functions, to handle retrieval of valid boundary box for data associated to an import done and thus with no more data in import transient tables. In this case, the function retrieves data from geom fields in the destination tables directly (e.g.: gn_synthese.synthese for destination "synthese", pr_occhab.t_stations for destination "occhab"). The destination table is retrieved as entity.get_destination_table().

## Commit [a0a3300](https://github.com/PnX-SI/GeoNature/commit/a0a3300c1d9b4adf7aedaa2fe236cfe9a9c70757) - feat(import): modify display logic of map for imported data":

Hide the section "Zone géographique" from the summary before import if the valid bbox is null.

2024-04-30 13:53 UTC, Pierre-Narcisi commented on backend/geonature/core/imports/bbox.py
> +    if not Key.IS_RELEVANT in infos:
Ca force un peut a déclarer ces fonction même si y'en a pas besoin non ? on pourrais juste ne pas lancer la fonction get_valid_bbox si les fonctions ne sont pas déclarer ?

2024-05-02 07:37 UTC, edelclaux commented on backend/geonature/core/gn_synthese/imports/__init__.py
Je suis tout à fait d'accord, c'est pas une fonction, c'est une variable type config, comme pour les statistiques.

Je voulais demander à Vincent s'il avait une idée derrière la tête avant de changer la forme.

2024-05-02 07:51 UTC, edelclaux commented on backend/geonature/core/imports/bbox.py
> +    if not Key.IS_RELEVANT in infos:
Dans le cas de aps de bbox, ça force à déclarer: 
```
def get_bbox_computation_infos():
    return {
        bbox.Key.IS_RELEVANT: False,
    }
```

J'aime bien l'explicite. Mais c'est vrai que c'est pas trés cohérent avec le reste. 
Je change !

2024-05-02 09:15 UTC, jacquesfize commented on backend/geonature/core/gn_synthese/imports/__init__.py
> +    return {
Pourquoi ne pas inclure ces dernières dans la configuration du module ?

2024-05-02 09:19 UTC, jacquesfize commented on backend/geonature/core/imports/bbox.py
> +class Key(str, Enum):
J'aime les `enum` :) Je me demande si ça serait intéressant d'étendre l'Enum pour toute les variables de configurations présents dans `__import__` ? Ça serait plus propre :)

2024-05-02 09:20 UTC, jacquesfize commented on contrib/gn_module_occhab/backend/gn_module_occhab/imports/__init__.py
> +def get_where_clause_id_import(imprt):
est-ce que l'on ferait pas un fonctionnement par défaut  qui s'appui sur des noms de colonnes (déclarés dans la config `__import__` du module ?

2024-05-02 10:23 UTC, edelclaux commented on backend/geonature/core/imports/bbox.py
> +class Key(str, Enum):
A voir dans le détail, mais à priori ça me parait une bonne idée. 
Je suis pas très fan des clefs de dictionnaire magique :) 


Par contre, c'est une tâche "housekeeping/refacto", indépendante des objectifs de celle la ! 
A vous de voir si vous voulez la porter à un sprint :)

2024-05-02 10:24 UTC, edelclaux commented on contrib/gn_module_occhab/backend/gn_module_occhab/imports/__init__.py
> +def get_where_clause_id_import(imprt):
Sans doute que oui. Je me suis pas trop penché sur cette partie la.

2024-05-14 09:03 UTC, jacquesfize commented on backend/geonature/core/imports/models.py
> +    def interface_import(self):
pourquoi ne pas surcharger __getattr__ ?:D ça part loin :D

2024-05-15 14:44 UTC, jacquesfize commented on backend/geonature/utils/metaclass_utils.py
> +    )  # class M_C
idem commentaire que j'ai oublié

2024-05-16 08:35 UTC, jacquesfize requested changes
Quelques commentaires à enlever et c'est tout bon pour moi :+1:

2024-05-16 08:35 UTC, jacquesfize commented on backend/geonature/utils/metaclass_utils.py
> +    )  # class M_C
```suggestion
    ) 
```

2024-05-16 08:35 UTC, jacquesfize commented on backend/geonature/core/imports/models.py
> +        print("DIRRRR", dir(self.module))
```suggestion
```

2024-05-16 09:05 UTC, merged