[IMPORT][OCCHAB] add default mapping
PnX-SI/GeoNature pull request #3127
Opened 2024-07-19 09:47 UTC by jacquesfize

This PR propose to include new mapping dedicated to the OccHab destination.

2024-08-14 14:04 UTC, bouttier requested changes
Pas de modèles dans les migrations !

2024-08-21 21:21 UTC, camillemonchicourt commented on contrib/gn_module_occhab/backend/gn_module_occhab/migrations/aed662bbd88a_add_default_mapping.py
> +            label="OccHab GeoNature",
Occhab

2024-08-21 21:23 UTC, camillemonchicourt commented on contrib/gn_module_occhab/backend/gn_module_occhab/migrations/aed662bbd88a_add_default_mapping.py
> +            label="Données Habitats SINP",
Je capte pas bien à quoi correspond cet autre mapping ?
Mais de ce que je comprends, il faudrait plutôt le nommer "Occurrences d'habitats SINP" ?

2024-09-14 15:52 UTC, bouttier reviewed
En sois OK mais plus simple de récupérer les tables par réflexivitées

2024-09-14 15:52 UTC, bouttier commented on contrib/gn_module_occhab/backend/gn_module_occhab/migrations/aed662bbd88a_add_default_mapping.py
> +from geonature.core.imports.models import Destination
```suggestion
```

2024-09-30 09:36 UTC, jacquesfize commented on contrib/gn_module_occhab/backend/gn_module_occhab/migrations/aed662bbd88a_add_default_mapping.py
> +from geonature.core.imports.models import Destination
Done

2024-09-30 09:36 UTC, jacquesfize commented on contrib/gn_module_occhab/backend/gn_module_occhab/migrations/aed662bbd88a_add_default_mapping.py
> +            label="OccHab GeoNature",
Done :heavy_check_mark:

2024-09-30 14:05 UTC, merged