Update https.rst for openssl
PnX-SI/GeoNature pull request #3134
Opened 2024-07-24 13:14 UTC by CynthiaBorotPNV

2024-07-25 11:50 UTC, jacquesfize requested changes

2024-07-25 11:50 UTC, jacquesfize commented on docs/https.rst
> +Cette documentation est indicative car elle ne concerne pas GeoNature. Elle donne quelques indications sur la mise en place d'un certificat SSL pour une application web servie par Apache.
```suggestion
Cette documentation est indicative car non-spécifique à GeoNature. Elle donne des indications sur la mise en place d'un certificat SSL pour une application web servie par Apache.
```

2024-07-25 11:50 UTC, jacquesfize commented on docs/https.rst
> +Source : https://korben.info/securiser-facilement-gratuitement-site-https.html
```suggestion
**Source.** `Sécuriser facilement et gratuitement un site avec HTTPS  <https://korben.info/securiser-facilement-gratuitement-site-https.html>`_
```

2024-07-25 11:50 UTC, jacquesfize commented on docs/https.rst
> +Cette procédure a été testée sur Debian 12 et Apache2 avec l'utilisation d'un certificat auto-signé. Cela signifier qu'une alerte sera envoyé aux navigatuers indiquant un manque de sécurisation du se
```suggestion
Cette procédure a été testée sur Debian 12 et Apache2 avec l'utilisation d'un certificat auto-signé. Cela signifie qu'une alerte sera envoyée aux navigateurs indiquant un manque de sécurisation du serveur.
```

2024-10-28 13:44 UTC, camillemonchicourt commented on docs/https.rst
> +**Source.** `Sécuriser facilement et gratuitement un site avec HTTPS  <https://korben.info/securiser-facilement-gratuitement-site-https.html>`_
```suggestion
**Source.** `Sécuriser facilement et gratuitement un site avec HTTPS <https://korben.info/securiser-facilement-gratuitement-site-https.html>`_
```

2024-10-28 13:45 UTC, camillemonchicourt commented on docs/https.rst
> +Cette procédure a été testée sur Debian 12 et Apache2 avec l'utilisation d'un certificat auto-signé. Cela signifie qu'une alerte sera envoyée aux navigateurs indiquant un manque de sécurisation du se
```suggestion

Cette procédure a été testée sur Debian 12 et Apache2 avec l'utilisation d'un certificat auto-signé. Cela signifie qu'une alerte sera envoyée aux navigateurs indiquant un manque de sécurisation du serveur.
```

2024-10-29 12:46 UTC, merged