Feat(import) add check and tests
PnX-SI/GeoNature pull request #3200
Opened 2024-09-24 08:45 UTC by Pierre-Narcisi

2024-09-24 09:26 UTC, jacquesfize commented on backend/geonature/core/imports/checks/sql/nomenclature.py
> +    other = TNomenclatures.query.filter(
A passer en SQLA 2.0 😸

2024-09-24 11:37 UTC, edelclaux commented on backend/geonature/core/imports/checks/sql/nomenclature.py
> +    other = TNomenclatures.query.filter(
he's back !

2024-09-27 11:23 UTC, bouttier requested changes

2024-09-27 11:23 UTC, bouttier commented on backend/geonature/tests/imports/files/occhab/valid_file.csv
> +Il y a ni UUID, ni id_origine : l’UUID sera généré.;OK !;OK !;;;VALID_DATASET_UUID;17/11/2023;17/11/2023;Toto;;POINT(3.634 44.399);St;;prairie;24;;10
```suggestion
technique collect vaut « autre » mais pas de précision fournise;OK !;CONDITIONAL_MANDATORY_FIELD_ERROR;;;VALID_DATASET_UUID;17/11/2023;17/11/2023;Toto;;POINT(3.634 44.399);St;;prairie;24;;10
```

2024-09-27 11:23 UTC, bouttier commented on backend/geonature/tests/imports/files/occhab/valid_file.csv
> +Il y a ni UUID, ni id_origine : l’UUID sera généré.;OK !;OK !;;;VALID_DATASET_UUID;17/11/2023;17/11/2023;Toto;;POINT(3.634 44.399);St;;prairie;24;squalala;10
```suggestion
technique collect vaut « autre » et une précision est bien fournies;OK !;OK !;;;VALID_DATASET_UUID;17/11/2023;17/11/2023;Toto;;POINT(3.634 44.399);St;;prairie;24;moyen précis;10
```

2024-10-01 12:36 UTC, merged